<template>
  <b-container fluid>
    <b-row>
      <h1>Markov Tunes</h1>
    </b-row>
    <b-row class="mb-5">
      <b-col class="explanation" md="5">
        <h2>Explanation</h2>
        <p>
          Markov Tunes is a random music generator that allows you to play
          melodies based on a Markov Chain.
        </p>
        <p>
          Markov Chains are a useful mechanism to simulate stochastic events,
          where the probability of an event is only dependent on the immediately
          previous one. They are represented with a probability matrix, which
          represents the transitions in a Finite Automata.
        </p>
        <h2>Matrix description</h2>
        <ul>
          <li>The <mark class="info">previous state</mark> probability row</li>
          <li>The <mark class="primary">current note</mark> being played</li>
          <li>
            The <mark class="success">current state</mark> probability row
          </li>
        </ul>
        <h2>Instructions</h2>
        <ul>
          <li>
            To randomly play a note generated by the Markov Chain, press
            <u>"Spacebar".</u> (You can also hold it down to keep the note going 👀).
          </li>
          <li>Click on <u>"Play"</u> to harmonize your tune</li>
        </ul>
      </b-col>
      <b-col md="7">
        <b-img
          class="main-img"
          src="/assets/keyboard.png"
          fluid
          alt="Keyboard"
        ></b-img>
      </b-col>
    </b-row>
    <b-row>
      <b-col md="6">
        <b-button v-on:click="changeState" :variant="playing ? 'danger' : 'success'">{{playing ? 'Stop' : 'Play'}}</b-button>
        <br /><br /><br />
        <h2>Tone</h2>
        <h4>D Major</h4>
        <br />
        <h2>Scale</h2>
        <h4>D, E, F#, G, A, B, C#</h4>
        <br />
        <h2>Chord progression</h2>
        <h4>Bm (vi), G (iv), D (i), A (v)</h4>
        <br />
        <h2>Current note</h2>
        <h4>{{ currNote }}</h4>
      </b-col>
      <b-col md="6">
        <b-table-simple>
          <b-thead head-variant="dark">
            <b-tr>
              <b-th></b-th>
              <b-th v-for="(n, i) in notes" :key="i">{{ n }}</b-th>
            </b-tr>
          </b-thead>
          <b-tbody>
            <b-tr v-for="(n, i) in transitionMatrix" :key="i">
              <b-th>{{ notes[i] }}</b-th>
              <b-td
                v-for="(k, j) in transitionMatrix[i]"
                :key="j"
                :variant="getCellColor(i, j)"
                >{{ k }}</b-td
              >
            </b-tr>
          </b-tbody>
        </b-table-simple>
      </b-col>
    </b-row>
    <br /><br />
    <b-row>
      <b-col class="attr">
        <h2>Attributions</h2>
        <br>
        <p>
          Author: Hugo Valdez @
          <a href="https://github.com/huguintoch/markov-tunes"
            >https://github.com/huguintoch/markov-tunes</a
          >
        </p>
        <p>
          Music library: Tone.js @
          <a href="https://github.com/Tonejs/Tone.js"
            >https://github.com/Tonejs/Tone.js</a
          >
        </p>
        <br>
        <p>*Site solely for educational purposes.</p>
      </b-col>
    </b-row>
  </b-container>
</template>

<script>
import * as Tone from "tone";
export default {
  name: "Main",
  data() {
    return {
     notes: [
      "C3", "C#3", "D3", "D#3", "E3",
      "F3", "F#3", "G3", "G#3", "A3",
      "A#3", "B3",
    ],
      autoPlayInterval: null,
      notesInScaleIndexes: [0, 2, 4, 5, 7, 9, 11],
      transitionMatrix: [
//  C    C#   D    D#   E    F    F#   G    G#   A    A#   B
  [ 0,   0,  0.1,  0,  0.3,  0.3, 0,  0.2,  0,  0.1,  0,  0  ], // C
  [ 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  0  ], // C#
  [ 0,   0,   0,   0,  0.4,  0.3, 0,  0.1,  0,  0.2,  0,  0  ], // D
  [ 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  0  ], // D#
  [ 0,   0,  0.1,  0,   0,   0.5, 0,  0.1,  0,  0.3,  0,  0  ], // E → F FUERTE
  [ 0,   0,  0.1,  0,  0.3,  0,   0,  0.3,  0,  0.2,  0,  0.1], // F
  [ 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  0  ], // F#
  [ 0,   0,  0.1,  0,  0.2,  0.2, 0,   0,   0,  0.4,  0,  0.1], // G
  [ 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  0  ], // G#
  [ 0,   0,  0.1,  0,  0.3,  0.3, 0,  0.2,  0,   0,   0,  0.1], // A
  [ 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  0  ], // A#
  [ 0,   0,  0.2,  0,  0.2,  0.1, 0,  0.2,  0,  0.3,  0,  0  ], // B
],
melodySynth: new Tone.Synth({
        oscillator: { type: "sawtooth" },
        envelope: {
          attack: 0.01,
          decay: 0.1,
          sustain: 0.5,
          release: 0.3,
        },
      }).toDestination(),
      playing: false,
      loop: null,
      pressed: false,
      prevIndex: 9,  // A3 es la tónica ahora
      currIndex: 9,
      nextIndex: 9,
      currNote: "A3",
    };
  },
  methods: {
    async changeState() {
      if (!this.playing) {
        await Tone.start();
        Tone.Transport.bpm.value = 95;
        this.chords();
        Tone.Transport.start();
        this.startAutoPlay(); 
      } else {
        Tone.Transport.stop();
        this.loop.dispose();
        this.stopAutoPlay();
      }
      this.playing = !this.playing;
    },
    chords() {
      let chordNum = 0;
      const chords = [
      ["A2", "E3", "G3"],   // Am  — bajo y oscuro
      ["F2", "C3", "F3"],   // F   — grave
      ["G2", "D3", "G3"],   // G   — tensión
      ["E2", "B2", "E3"],   // Em  — resuelve oscuro
      ];
      const synth = new Tone.PolySynth().toDestination();
      synth.volume.value = -6;
      this.loop = new Tone.Loop(() => {
        synth.triggerAttackRelease(chords[chordNum], "2m");
        chordNum = (chordNum + 1) % 4;
      }, "2m").start(0);
    },
    attack() {
      this.melodySynth.triggerAttack(this.notes[this.nextIndex]);
    },
    release() {
      this.melodySynth.triggerRelease();
    },
    getNextnextIndex() {
      let rand = Math.random();
      rand -= 0.16;
      return rand <= 0 ? 0 : 1 + Math.floor(rand / 0.14);
    },
    getNextNoteIndex() {
      const row = this.transitionMatrix[this.currIndex];
      const rand = Math.random();
      let cumulative = 0;
      for (let i = 0; i < row.length; i++) {
        cumulative += row[i];
        if (rand < cumulative) {
          return i;
        }
      }
      // fallback: devuelve la tónica
      return this.notesInScaleIndexes[0];
    },
    startAutoPlay() {
  const noteDurations = [200, 200, 400, 200]; // patrón rítmico irregular
  let beat = 0;
  this.autoPlayInterval = setInterval(() => {
    this.currNote = this.notes[this.nextIndex];
    this.attack();
    this.prevIndex = this.currIndex;
    this.currIndex = this.nextIndex;
    this.nextIndex = this.getNextNoteIndex();

    const dur = noteDurations[beat % noteDurations.length];
    beat++;
    setTimeout(() => this.release(), dur - 50);
  }, 250); // negra a ~95 BPM con subdivisión
},
stopAutoPlay() {
  clearInterval(this.autoPlayInterval);
  this.autoPlayInterval = null;
  this.release();
},
    getCellColor(i, j) {
      if (i == this.prevIndex && j == this.currIndex) {
        return "primary";
      } else if (i == this.prevIndex) {
        return "info";
      } else if (i == this.currIndex) {
        return "success";
      } else {
        return "";
      }
    },
  },
  created() {
    window.addEventListener("keydown", (e) => {
      if (e.key == " " && !this.pressed) {
        e.preventDefault();
        this.pressed = true;
        this.currNote = this.notes[this.nextIndex];
        this.attack();
        this.prevIndex = this.currIndex;
        this.currIndex = this.nextIndex;
        this.nextIndex = this.getNextNoteIndex();
      }
    });
    window.addEventListener("keyup", (e) => {
      if (e.key == " ") {
        e.preventDefault();
        this.release();
        this.pressed = false;
      }
    });
  },
};
</script>

<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Space+Mono:wght@700&display=swap");
* {
  font-family: "Space Mono", monospace;
}
h1 {
  font-size: 3rem;
}
.explanation {
  padding: 3rem;
  padding-top: 0;
}
.explanation > h2,
h3,
p,
ul {
  text-align: start;
}
.explanation > h2 {
  margin-top: 1rem;
}
.explanation > ul > li {
  margin-bottom: 0.75rem;
}
.attr > p {
  text-align: center;
}
.primary {
  background-color: #007bff33;
}
.info {
  background-color: #17a2b833;
}
.success {
  background-color: #28a74533;
}
</style>
