<template>
  <b-container fluid>
    <b-row>
      <h1>Markov Tunes</h1>
    </b-row>
    <b-row class="mb-5">
      <b-col class="explanation" md="5">
        <h2>Explanation</h2>
        <p>
          Markov Tunes is a random music generator that allows you to play
          melodies based on a Markov Chain.
        </p>
        <p>
          Markov Chains are a useful mechanism to simulate stochastic events,
          where the probability of an event is only dependent on the immediately
          previous one. They are represented with a probability matrix, which
          represents the transitions in a Finite Automata.
        </p>
        <h2>Matrix description</h2>
        <ul>
          <li>The <mark class="info">previous state</mark> probability row</li>
          <li>The <mark class="primary">current note</mark> being played</li>
          <li>
            The <mark class="success">current state</mark> probability row
          </li>
        </ul>
        <h2>Instructions</h2>
        <ul>
          <li>
            To randomly play a note generated by the Markov Chain, press
            <u>"Spacebar".</u> (You can also hold it down to keep the note going
            👀).
          </li>
          <li>Click on <u>"Play"</u> to harmonize your tune</li>
        </ul>
      </b-col>
      <b-col md="7">
        <b-img
          class="main-img"
          src="/assets/keyboard.png"
          fluid
          alt="Keyboard"
        ></b-img>
      </b-col>
    </b-row>
    <b-row>
      <b-col md="6">
        <b-button
          v-on:click="changeState"
          :variant="playing ? 'danger' : 'success'"
          >{{ playing ? "Stop" : "Play" }}</b-button
        >
        <br /><br /><br />
        <h2>Tone</h2>
        <h4>Chromatic</h4>
        <br />
        <h2>Current Genre</h2>
        <h4
          style="color: #FF6B9D; text-transform: uppercase; font-weight: bold;"
        >
          {{ currentGenre }}
        </h4>
        <br />
        <h2>Current note</h2>
        <h4>{{ currNote }}</h4>
        <br />
        <h2>Transición de Markov</h2>
        <p
          style="font-size: 0.85rem; background: #f5f5f5; padding: 0.5rem; border-radius: 5px;"
        >
          {{ transitionLog }}
        </p>
      </b-col>
      <b-col md="6">
        <b-table-simple>
          <b-thead head-variant="dark">
            <b-tr>
              <b-th></b-th>
              <b-th v-for="(n, i) in notes" :key="i">{{ n }}</b-th>
            </b-tr>
          </b-thead>
          <b-tbody>
            <b-tr v-for="(n, i) in transitionMatrix" :key="i">
              <b-th>{{ notes[i] }}</b-th>
              <b-td
                v-for="(k, j) in transitionMatrix[i]"
                :key="j"
                :variant="getCellColor(i, j)"
                >{{ k }}</b-td
              >
            </b-tr>
          </b-tbody>
        </b-table-simple>
      </b-col>
    </b-row>
    <br /><br />
    <b-row>
      <b-col class="attr">
        <h2>Attributions</h2>
        <br />
        <p>
          Author: Hugo Valdez @
          <a href="https://github.com/huguintoch/markov-tunes"
            >https://github.com/huguintoch/markov-tunes</a
          >
        </p>
        <p>
          Music library: Tone.js @
          <a href="https://github.com/Tonejs/Tone.js"
            >https://github.com/Tonejs/Tone.js</a
          >
        </p>
        <br />
        <p>*Site solely for educational purposes.</p>
      </b-col>
    </b-row>
  </b-container>
</template>

<script>
import * as Tone from "tone";
export default {
  name: "Main",
  data() {
    return {
      notes: [
        "C4",
        "C#4", //1
        "D4", //2
        "D#4",
        "E4", //4
        "F4",
        "F#4", //6
        "G4", //7
        "G#4",
        "A4", //9
        "A#4",
        "B4", //11
      ],
<<<<<<< Updated upstream
      notesInScaleIndexes: [2, 1, 4, 6, 7, 9, 11],
      transitionMatrix: [
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
        [0, 0.14, 0.16, 0, 0.14, 0, 0.14, 0.14, 0, 0.14, 0, 0.14],
      ],
=======
      notesInScaleIndexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
      markovMatrices: {
        rock: [
          [
            0.08,
            0.08,
            0.15,
            0.05,
            0.15,
            0.12,
            0.07,
            0.12,
            0.05,
            0.1,
            0.02,
            0.0,
          ],
          [
            0.08,
            0.08,
            0.15,
            0.05,
            0.15,
            0.12,
            0.07,
            0.12,
            0.05,
            0.1,
            0.02,
            0.0,
          ],
          [0.08, 0.08, 0.1, 0.05, 0.2, 0.12, 0.07, 0.12, 0.05, 0.1, 0.02, 0.01],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.1, 0.05, 0.1, 0.05, 0.1, 0.3, 0.05, 0.15, 0.05, 0.2, 0.05, 0.0],
          [0.08, 0.08, 0.1, 0.05, 0.15, 0.1, 0.07, 0.2, 0.05, 0.15, 0.01, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.1, 0.05, 0.15, 0.05, 0.1, 0.15, 0.05, 0.1, 0.05, 0.3, 0.05, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.1, 0.05, 0.15, 0.05, 0.15, 0.2, 0.05, 0.2, 0.05, 0.1, 0.0, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.08, 0.08, 0.1, 0.05, 0.2, 0.12, 0.07, 0.15, 0.05, 0.1, 0.0, 0.0],
        ],
        pop: [
          [0.1, 0.05, 0.15, 0.05, 0.15, 0.1, 0.05, 0.2, 0.05, 0.1, 0.0, 0.0],
          [0.1, 0.05, 0.15, 0.05, 0.15, 0.1, 0.05, 0.2, 0.05, 0.1, 0.0, 0.0],
          [0.1, 0.05, 0.1, 0.05, 0.2, 0.1, 0.05, 0.15, 0.05, 0.15, 0.0, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.1, 0.05, 0.1, 0.05, 0.1, 0.15, 0.05, 0.2, 0.05, 0.15, 0.0, 0.0],
          [0.1, 0.05, 0.1, 0.05, 0.15, 0.1, 0.05, 0.2, 0.05, 0.15, 0.0, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.1, 0.05, 0.15, 0.05, 0.15, 0.1, 0.05, 0.1, 0.05, 0.15, 0.0, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.1, 0.05, 0.15, 0.05, 0.15, 0.1, 0.05, 0.15, 0.05, 0.1, 0.0, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.1, 0.05, 0.1, 0.05, 0.15, 0.1, 0.05, 0.15, 0.05, 0.15, 0.0, 0.0],
        ],
        jazz: [
          [
            0.09,
            0.08,
            0.09,
            0.08,
            0.12,
            0.12,
            0.08,
            0.12,
            0.08,
            0.1,
            0.04,
            0.0,
          ],
          [
            0.09,
            0.08,
            0.09,
            0.08,
            0.12,
            0.12,
            0.08,
            0.12,
            0.08,
            0.1,
            0.04,
            0.0,
          ],
          [
            0.09,
            0.08,
            0.09,
            0.08,
            0.12,
            0.12,
            0.08,
            0.12,
            0.08,
            0.1,
            0.04,
            0.0,
          ],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [
            0.09,
            0.08,
            0.09,
            0.08,
            0.12,
            0.12,
            0.08,
            0.12,
            0.08,
            0.1,
            0.04,
            0.0,
          ],
          [
            0.09,
            0.08,
            0.09,
            0.08,
            0.12,
            0.12,
            0.08,
            0.12,
            0.08,
            0.1,
            0.04,
            0.0,
          ],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [
            0.09,
            0.08,
            0.09,
            0.08,
            0.12,
            0.12,
            0.08,
            0.12,
            0.08,
            0.1,
            0.04,
            0.0,
          ],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [
            0.09,
            0.08,
            0.09,
            0.08,
            0.12,
            0.12,
            0.08,
            0.12,
            0.08,
            0.1,
            0.04,
            0.0,
          ],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [
            0.09,
            0.08,
            0.09,
            0.08,
            0.12,
            0.12,
            0.08,
            0.12,
            0.08,
            0.1,
            0.04,
            0.0,
          ],
        ],
        explosive: [
          [0.2, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.05, 0.0],
          [0.2, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.05, 0.0],
          [0.15, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.15, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.0],
          [0.15, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.2, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.1, 0.05, 0.05, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.2, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.05, 0.0],
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
          [0.15, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.0],
        ],
      },
      transitionMatrix: [],
      currentGenre: "rock",
      genreSequence: ["rock", "pop", "jazz", "explosive"],
      genreIndex: 0,
      noteCount: 0,
      genreChangeInterval: 16,
>>>>>>> Stashed changes
      melodySynth: new Tone.Synth().toDestination(),
      autoLoop: null,
      playing: false,
      loop: null,
      pressed: false,
      prevIndex: 2,
      currIndex: 2,
      nextIndex: 2,
      currNote: "D4",
      transitionLog: "Cadena de Markov iniciada...",
      noteTimeInterval: "8n", // Duración de cada nota (negra = 4n, corchea = 8n)
      autoPlayEnabled: true,
    };
  },
  methods: {
    changeGenre() {
      this.genreIndex = (this.genreIndex + 1) % this.genreSequence.length;
      this.currentGenre = this.genreSequence[this.genreIndex];
      this.transitionMatrix = JSON.parse(
        JSON.stringify(this.markovMatrices[this.currentGenre]),
      );
      console.log(`🎵 Género cambió a: ${this.currentGenre.toUpperCase()}`);
      this.transitionLog = `Género cambió a: ${this.currentGenre}`;
    },
    async changeState() {
      if (!this.playing) {
        await Tone.start();
        this.currentGenre = "rock";
        this.transitionMatrix = JSON.parse(
          JSON.stringify(this.markovMatrices[this.currentGenre]),
        );
        Tone.Transport.bpm.value = 120;
        this.chords();
        this.startAutoPlay(); // Iniciar reproducción automática
        Tone.Transport.start();
      } else {
        Tone.Transport.stop();
        this.loop.dispose();
        this.autoLoop.stop(); // Detener loop automático
        this.autoLoop.dispose();
      }
      this.playing = !this.playing;
    },
    startAutoPlay() {
      // Loop que genera notas automáticamente cada X tiempo
      this.autoLoop = new Tone.Loop(() => {
        if (this.autoPlayEnabled) {
          this.currNote = this.notes[this.nextIndex];
          this.attack();
          Tone.Transport.bpm.value > 0 &&
            setTimeout(
              () => this.release(),
              Tone.Time(this.noteTimeInterval).toMilliseconds(),
            );
          this.prevIndex = this.currIndex;
          this.currIndex = this.nextIndex;
          this.nextIndex = this.getNextNoteIndex();

          // Cambiar género cada 16 notas
          this.noteCount++;
          if (this.noteCount % this.genreChangeInterval === 0) {
            this.changeGenre();
          }
        }
      }, this.noteTimeInterval).start(0);
    },
    /**chords() {
      let chordNum = 0;
      const chords = [
        ["B3", "D3", "F#3"], // Bm (vi)
        ["G3", "B3", "D3"], // G (iv)
        ["D3", "F#3", "A3"], // D (i)
        ["A3", "C#3", "E3"], // A (v)
      ];
      const synth = new Tone.PolySynth().toDestination();
      synth.volume.value = -6;
      this.loop = new Tone.Loop(() => {
        synth.triggerAttackRelease(chords[chordNum], "2m");
        chordNum = (chordNum + 1) % 4;
      }, "2m").start(0);
    },*/
    chords() {
      let chordNum = 0;

      // Progresión que mezcla géneros
      const chords = [
        // Rock clásico
        ["A2", "E2", "A2"], // A5 power chord
        ["G2", "D2", "G2"], // G5 power chord

        // Pop
        ["D3", "F#3", "A3"], // D Major (I)
        ["G3", "B3", "D3"], // G Major (IV)

        // Jazz (séptimas)
        ["C3", "E3", "G3", "Bb2"], // Cmaj7
        ["F3", "A3", "C3", "E3"], // Fmaj7

        // Explosivo
        ["B2", "D#3", "F#3"], // Bm disminuido (caótico)
        ["C2", "E2", "Ab2"], // Acordes con tensión
      ];

      const synth = new Tone.PolySynth().toDestination();
      synth.volume.value = -6;

      this.loop = new Tone.Loop(() => {
        synth.triggerAttackRelease(chords[chordNum], "2m");
        chordNum = (chordNum + 1) % chords.length;
      }, "2m").start(0);
    },
    attack() {
      this.melodySynth.triggerAttack(this.notes[this.nextIndex]);
    },
    release() {
      this.melodySynth.triggerRelease();
    },
<<<<<<< Updated upstream
    getNextnextIndex() {
      let rand = Math.random();
      rand -= 0.16;
      return rand <= 0 ? 0 : 1 + Math.floor(rand / 0.14);
=======
    getNextNoteIndex() {
      const row = this.transitionMatrix[this.currIndex];
      const randomValue = Math.random();
      let cumulativeProbability = 0;
      for (let i = 0; i < row.length; i++) {
        cumulativeProbability += row[i];
        if (randomValue < cumulativeProbability) {
          const fromNote = this.notes[this.currIndex];
          const toNote = this.notes[i];
          const probability = row[i].toFixed(2);
          this.transitionLog = `${fromNote} → ${toNote} (P: ${probability})`;
          console.log(`Markov: ${fromNote} → ${toNote} [Prob: ${probability}]`);
          return i;
        }
      }
      return this.currIndex;
>>>>>>> Stashed changes
    },
    getCellColor(i, j) {
      if (i == this.prevIndex && j == this.currIndex) {
        return "primary";
      } else if (i == this.prevIndex) {
        return "info";
      } else if (i == this.currIndex) {
        return "success";
      } else {
        return "";
      }
    },
  },
  created() {
    // El spacebar ahora es opcional - puede reproducir manual o automático
    window.addEventListener("keydown", (e) => {
      if (e.key == " " && !this.pressed && this.playing) {
        e.preventDefault();
        this.pressed = true;
<<<<<<< Updated upstream
        this.currNote = this.notes[this.nextIndex];
        this.attack();
        this.prevIndex = this.currIndex;
        this.currIndex = this.nextIndex;
        this.nextIndex = this.notesInScaleIndexes[this.getNextnextIndex()];
=======
        this.autoPlayEnabled = false; // Pausar auto-play cuando el usuario presiona
>>>>>>> Stashed changes
      }
    });
    window.addEventListener("keyup", (e) => {
      if (e.key == " " && this.playing) {
        e.preventDefault();
        this.pressed = false;
        this.autoPlayEnabled = true; // Reanudar auto-play
      }
    });
  },
};
</script>

<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Space+Mono:wght@700&display=swap");
* {
  font-family: "Space Mono", monospace;
}
h1 {
  font-size: 3rem;
}
.explanation {
  padding: 3rem;
  padding-top: 0;
}
.explanation > h2,
h3,
p,
ul {
  text-align: start;
}
.explanation > h2 {
  margin-top: 1rem;
}
.explanation > ul > li {
  margin-bottom: 0.75rem;
}
.attr > p {
  text-align: center;
}
.primary {
  background-color: #007bff33;
}
.info {
  background-color: #17a2b833;
}
.success {
  background-color: #28a74533;
}
</style>
